import * as React from 'react';
import { ChevronLeft, ChevronRight } from 'lucide-react';
import { DayPicker } from 'react-day-picker';
import { cn } from '@/lib/utils';

export interface CalendarProps extends React.ComponentProps<typeof DayPicker> {}

function Calendar({ className, classNames, showOutsideDays = true, ...props }: CalendarProps) {
    return <DayPicker showOutsideDays={showOutsideDays} className={cn('rdp-new w-fit p-3 [--cell-size:--spacing(8)] [--rdp-accent-color:theme(color.primary)]', className)} classNames={{ months: 'flex flex-col sm:flex-row gap-4', month: 'flex flex-col gap-4', month_caption: 'flex justify-center pt-1 relative items-center w-full', caption_label: 'flex items-center gap-1 text-sm font-medium [&>select]:appearance-none [&>select]:bg-background [&>select]:border [&>select]:border-input [&>select]:h-7 [&>select]:rounded-md [&>select]:px-2 [&>select]:text-sm', nav: 'absolute inset-x-0 top-1 flex items-center justify-between px-1', button_previous: 'inline-flex h-7 w-7 items-center justify-center rounded-md border border-input bg-background hover:bg-accent transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50', button_next: 'inline-flex h-7 w-7 items-center justify-center rounded-md border border-input bg-background hover:bg-accent transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50', month_grid: 'w-full border-collapse', weekdays: 'flex', weekday: 'text-muted-foreground rounded-md w-8 font-normal text-[0.8rem] flex-1 flex items-center justify-center', week: 'flex w-full mt-2', day: 'relative size-8 p-0 text-center text-sm flex-1', day_button: 'size-8 mx-auto inline-flex items-center justify-center rounded-md font-normal hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring transition-colors aria-selected:bg-primary aria-selected:text-primary-foreground aria-selected:opacity-100', selected: '[&>button]:bg-primary [&>button]:text-primary-foreground [&>button]:hover:bg-primary [&>button]:hover:text-primary-foreground', today: '[&>button]:bg-accent [&>button]:text-accent-foreground', outside: 'text-muted-foreground opacity-50', disabled: 'text-muted-foreground opacity-50', hidden: 'invisible', dropdowns: 'flex w-full items-center justify-center gap-2', dropdown: 'inline-flex h-7 items-center justify-between rounded-md border border-input bg-background px-2 text-sm shadow-xs focus:outline-none focus:ring-2 focus:ring-ring', dropdown_month: 'inline-flex h-7 items-center justify-between rounded-md border border-input bg-background px-2 text-sm shadow-xs focus:outline-none focus:ring-2 focus:ring-ring', dropdown_year: 'inline-flex h-7 items-center justify-between rounded-md border border-input bg-background px-2 text-sm shadow-xs focus:outline-none focus:ring-2 focus:ring-ring', ...classNames }} components={{ Chevron: ({ orientation }) => orientation === 'left' ? <ChevronLeft className="size-4" /> : <ChevronRight className="size-4" /> }} {...props} />;
}

export { Calendar };
